export const tools = [
  { name: "Merge PDF", link: "/tools/merge", icon: "call_merge", desc: "Combine PDFs in the order you want easily." },
  { name: "Split PDF", link: "/tools/split", icon: "call_split", desc: "Separate pages into independent files." },
  // { name: "Compress PDF", link: "/tools/compress", icon: "folder_zip", desc: "Reduce file size while optimizing quality." },
  { name: "PDF to Word", link: "/tools/pdf-to-word", icon: "description", desc: "Convert PDF to Word with accuracy." },
  { name: "Word to PDF", link: "/tools/word-to-pdf", icon: "article", desc: "Convert DOCX files to PDF format." },
  { name: "Edit PDF", link: "/tools/edit", icon: "edit_document", desc: "Add text, images, and annotations." },
  { name: "PDF to Image", link: "/tools/pdf-to-jpg", icon: "image", desc: "Extract images or convert pages to JPG." },
  { name: "Crop PDF", link: "/tools/crop", icon: "crop", desc: "Crop PDF pages to a specific size." },
  { name: "Image to PDF", link: "/tools/jpg-to-pdf", icon: "collections", desc: "Convert images to PDF in seconds." },
  { name: "Sign PDF", link: "/tools/sign", icon: "ink_pen", desc: "Sign documents and request signatures." },
  { name: "Watermark", link: "/tools/watermark", icon: "branding_watermark", desc: "Stamp images or text over PDFs." },
  { name: "Rotate PDF", link: "/tools/rotate", icon: "rotate_right", desc: "Rotate multiple documents at once." },
  // { name: "Protect PDF", link: "/tools/protect", icon: "lock", desc: "Encrypt PDF with a password." },
  // { name: "Organize PDF", link: "/tools/organize", icon: "sort", desc: "Sort, delete or add PDF pages." },
  // { name: "PDF to PDF/A", link: "/tools/pdf-to-pdfa", icon: "verified", desc: "Long-term archiving standards." },
  // { name: "Repair PDF", link: "/tools/repair", icon: "build", desc: "Recover data from corrupt PDF files." },
  // { name: "Page Numbers", link: "/tools/page-number", icon: "format_list_numbered", desc: "Add page positions and typography." },
  // { name: "OCR PDF", link: "/tools/ocr", icon: "find_in_page", desc: "Make scanned text searchable." },
  // { name: "Compare PDF", link: "/tools/compare", icon: "compare_arrows", desc: "Show changes side-by-side." },
  // { name: "Redact PDF", link: "/tools/redact", icon: "ink_eraser", desc: "Permanently remove sensitive info." },
];
